---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.4
    driver:
      box: fgrehm/centos-6-64-lxc
      provider: lxc
    run_list:
      - recipe[yum]

suites:
- name: default
  run_list:
    - recipe[monitor::master]
    - recipe[monitor::linux]
    - recipe[monitor::redis]
    - recipe[monitor::rabbitmq]
  attributes:
    apt:
     compile_time_update: true
    authorization:
      sudo:
        users: ["vagrant", "kitchen"]
        passwordless: true
        include_sudoers_d: true
    monitor:
      use_nagios_plugins: false
      use_system_profile: true
      use_statsd_input: true
